### ISSUE TITLE
Error in countdown approach? 

### ISSUE THREAD

**Issue by sdaweee** [EarnForex/TDSequentialUltimate#1]
Hello, EarnForex Dev team!

It has been a while since I have read the Tom's book and was looking for an open source solution.
Pinescript version from a guy named **glaz** looked interesting to me. Until today I found your code and wish to thank you as other devs sell this inducator and there is only mq4 version on the net.

I'm not a big coder so far with mql5 just a couple of months, frankly speaking, but I couldn't have noticed that there are differencies in your version and the glaz's.
https://www.tradingview.com/script/r3MXuoYt-TD-Sequential/

The difference between versions could be due to different trading venues and trading days (e.g. BTC/USD doesn't trade in weekend in FOREX but does in native crypto market)
That is why I took exectly the same data avaliable to me in TradingView and MT5 which is USD/RUB_TOM.
Have a look on the screenshots below.

![TV](https://user-images.githubusercontent.com/49559429/99802783-58f52580-2b49-11eb-9fd2-72d2b4b465d8.png)
![MT5](https://user-images.githubusercontent.com/49559429/99802789-5a265280-2b49-11eb-9f17-d07cd24b592c.png)

![photo5314277230387508524](https://user-images.githubusercontent.com/49559429/99803349-57782d00-2b4a-11eb-964b-4d08002f865f.jpg)

![photo5314277230387508523](https://user-images.githubusercontent.com/49559429/99803347-56df9680-2b4a-11eb-8604-f5d5ddff8046.jpg)

I'll try to figure the differenceis out in the next week but maybe you will cope with it faster.

**Comment by EarnForex** [comment]
I have no idea how the PineScript's TD Sequential works, but the Countdown bar #1 you marked at the bottom of your post is completely valid according to TD's rules. For Sell Countdown, the Close of the bar is compared to the High of two bars earlier - in this case Close[0] >= High[2].

**Comment by sdaweee** [comment]
thank you for the prompt reply. The issue can be closed
