### ISSUE TITLE
Perfected bars in TD logic - visuals 

### ISSUE THREAD

**Issue by Saltyn** [EarnForex/TDSequentialUltimate#2]
Sir/madam, pls modify indicator to make "perfected" bars #8 and #9 different shape/color
Thanks in advance
Oleksandr

amedvedyev@gmail.com
+ 380977301013 - WhatsApp, Viber, Telegram, Signal

**Comment by EarnForex** [comment]
But why?

**Comment by Saltyn** [comment]
It's critical to differentiate for better position entries - need visuals on chart

For active sell Signal
 -- "Perfected bar #8" of Sell-setup - if high of bar #8 > highs of #6 and #7
 -- "Perfected bar #9" of Sell-setup - if high of bar #9 > highs of #6 and #7 
 
 For active buy Signal
 -- "Perfected bar #8" of Buy-setup - if low of bar #8 < lows of #6 and #7
 -- "Perfected bar #9" of Buy-setup - if low of bar #9 < lows of #6 and #7
 
 Your attention this request would be greatly appreciated
 
 Thanks!
 🙂
 
 Oleksandr
 
 https://www.linkedin.com/in/oleksandr-medviediev-079891104/
 https://www.facebook.com/oleksandr.medviediev

**Comment by EarnForex** [comment]
A perfected bar is already getting highlighted with an arrow. Why modify its shape or color?

**Comment by Saltyn** [comment]
Oh, Arrow!!
 -- sorry (didn't realise)
Thanks!
🙂
